apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: ${dockerHubUsername}/sample-app:v1
          env:
            - name: APP_NAME
              value: "sample-app"
            - name: TEST_ME
              value: "Hello, world!"
            - name: K8_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "4444"
          ports:
            - containerPort: 4444
              name: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: sample-app
  selector:
    app: sample-app
